# Generated by Django 4.2.6 on 2023-10-28 06:39

import django.contrib.gis.db.models.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Facility',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50)),
                ('types', models.CharField(choices=[('gov', 'Pemerintahan'), ('public', 'Fasilitas Umum'), ('restaurant', 'Restaurant'), ('smoke', 'Smoking Area')], max_length=20)),
                ('status', models.CharField(choices=[('proposed', 'Proposed'), ('under_review', 'Under Review'), ('planned', 'Planned'), ('construction', 'Under Construction'), ('completed', 'Completed')], default='Proposed', max_length=20)),
                ('open', models.BooleanField(default=False)),
                ('location', django.contrib.gis.db.models.fields.PointField(srid=4326)),
            ],
        ),
    ]
